nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ["http://localhost:4200"]
    #['%env(CORS_ALLOW_ORIGIN)%']
    allow_methods: ["GET", "POST", "PUT", "DELETE"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: ["Link"]
    max_age: 3600
  paths:
    "^/api/":
      allow_origin: ["http://localhost:4200"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allow_headers: ["Content-Type", "Authorization"]
      max_age: 3600
