controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

login_api:
  path: /api/login

afficher_commentaires:
  path: /api/commentaires
  controller: App\Controller\CommentaireController::indexapi
  methods: [GET]

afficher_livres:
  path: /api/livres
  controller: App\Controller\LivreController::indexapi
  methods: [GET]

supprimer_commentaire:
  path: /api/commentaire/{id}/supprimer
  controller: App\Controller\CommentaireController::deleteapi
  methods: [POST]
